on:
  workflow_dispatch:

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Use API
        env:
          AUTH_TOKEN: $GITHUB_TOKEN
        run:
          python main.py



