on:
  workflow_dispatch:

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          FRESHDESK_KEY: ${{ secrets.API_KEY }}
        run:
          python start.py



